%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PSYCH 221 : Google Pixel 4A Noise Model - Read Noise Estimation
% Authors : Melissa Horowitz, Joey Yurgelon
% Date : 11/3/2020
% Required File Structure : 
%          See 'project/README.txt' - MATLAB
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Load in the specific structure generated by the GenerateDataStructures
% script. This takes a long time. Load it in and then manipulate the data.
close all
clear all
clc

%load('Z:\DarkCurrentRate_Data')
load('DarkCurrentRate_Data')

%% Manipulation of the data. 

T = struct2table(data_55S); % convert the struct array to a table
data_55T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_99S); % convert the struct array to a table
data_99T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_198S); % convert the struct array to a table
data_198T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_299S); % convert the struct array to a table
data_299T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_395S); % convert the struct array to a table
data_395T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_798S); % convert the struct array to a table
data_798T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

j = 1;
 for i = 1:5:length(data_55T.exposureTime)
     x1 = data_55S(i);
     x2 = data_55S(i+1);
     x3 = data_55S(i+2);
     x4 = data_55S(i+3);
     x5 = data_55S(i+4);
     
     data_55S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_55S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_55S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_55S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_99T.exposureTime)
     x1 = data_99S(i);
     x2 = data_99S(i+1);
     x3 = data_99S(i+2);
     x4 = data_99S(i+3);
     x5 = data_99S(i+4);
     
     data_99S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_99S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_99S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_99S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_198T.exposureTime)
     x1 = data_198S(i);
     x2 = data_198S(i+1);
     x3 = data_198S(i+2);
     x4 = data_198S(i+3);
     x5 = data_198S(i+4);
     
     data_198S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_198S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_198S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_198S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_299T.exposureTime)
     x1 = data_299S(i);
     x2 = data_299S(i+1);
     x3 = data_299S(i+2);
     x4 = data_299S(i+3);
     x5 = data_299S(i+4);
     
     data_299S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_299S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_299S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_299S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     j = j + 1;  
 end
 
  j = 1;
 for i = 1:5:length(data_395T.exposureTime)
     x1 = data_395S(i);
     x2 = data_395S(i+1);
     x3 = data_395S(i+2);
     x4 = data_395S(i+3);
     x5 = data_395S(i+4);
     
     data_395S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_395S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_395S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_395S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_798T.exposureTime)
     x1 = data_798S(i);
     x2 = data_798S(i+1);
     x3 = data_798S(i+2);
     x4 = data_798S(i+3);
     x5 = data_798S(i+4);
     
     data_798S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_798S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_798S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_798S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     j = j + 1;  
 end
 
%% 
T = struct2table(data_55S_avg); % convert the struct array to a table
data_55T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_99S_avg); % convert the struct array to a table
data_99T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_198S_avg); % convert the struct array to a table
data_198T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_299S_avg); % convert the struct array to a table
data_299T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_395S_avg); % convert the struct array to a table
data_395T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_798S_avg); % convert the struct array to a table
data_798T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

% NON-NORMALIZED ---- SENSOR ARRAY
figure(1)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.imgMean, 'r', 'DisplayName', '55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', '55')
theString = sprintf('55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-1*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.imgMean, 'r', 'DisplayName', '99')
plot(data_99T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', '99')
theString = sprintf('99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-2*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.imgMean, 'g', 'DisplayName', '198')
plot(data_198T_avg.exposureTime, orig1, '--g', [0 20e-3], xtnd1, '--g', 'DisplayName', '198')
theString = sprintf('198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-3*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.imgMean, 'b', 'DisplayName', '299')
plot(data_299T_avg.exposureTime, orig1, '--b', [0 15e-3], xtnd1, '--b', 'DisplayName', '299')
theString = sprintf('299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-4*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.imgMean, 'c', 'DisplayName', '395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', '395')
theString = sprintf('395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-5*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.imgMean, 'm', 'DisplayName', '798')
plot(data_798T_avg.exposureTime, orig2,'--m', [0 5e-3], xtnd2, '--m', 'DisplayName', '798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (64.05-6*0.005), theString, 'FontSize', 12);
title('DN vs. Exposure Time (s) : Sensor Array (Not Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off

% NORMALIZED ------ SENSOR ARRAY
figure(2)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
errorbar(data_55T_avg.exposureTime, data_55T_avg.imgMeanNorm, data_55T_avg.imgSTDNorm, '--r', 'DisplayName', '55')
%scatter(data_55T_avg.exposureTime, data_55T_avg.imgMeanNorm, 'r', 'DisplayName', '55')
plot(data_55T_avg.exposureTime, orig1, '--', [0 60e-3], xtnd1, '--r', 'DisplayName', '55')
theString = sprintf('55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (1-1*0.05), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
errorbar(data_99T_avg.exposureTime, data_99T_avg.imgMeanNorm, data_99T_avg.imgSTDNorm, '--g', 'DisplayName', '99')
%scatter(data_99T_avg.exposureTime, data_99T_avg.imgMeanNorm, 'r', 'DisplayName', '99')
plot(data_99T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', '99')
theString = sprintf('99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (1-2*0.05), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
errorbar(data_198T_avg.exposureTime, data_198T_avg.imgMeanNorm, data_198T_avg.imgSTDNorm, '--b',  'DisplayName', '198')
%scatter(data_198T_avg.exposureTime, data_198T_avg.imgMeanNorm, 'g', 'DisplayName', '198')
plot(data_198T_avg.exposureTime, orig1, '--b', [0 20e-3], xtnd1, '--b', 'DisplayName', '198')
theString = sprintf('198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (1-3*0.05), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
errorbar(data_299T_avg.exposureTime, data_299T_avg.imgMeanNorm, data_299T_avg.imgSTDNorm, '--c','DisplayName', '299')
%scatter(data_299T_avg.exposureTime, data_299T_avg.imgMeanNorm, 'b', 'DisplayName', '299')
plot(data_299T_avg.exposureTime, orig1, '--c', [0 15e-3], xtnd1, '--c', 'DisplayName', '299')
theString = sprintf('299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (1-4*0.05), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
errorbar(data_395T_avg.exposureTime, data_395T_avg.imgMeanNorm, data_395T_avg.imgSTDNorm, '--m','DisplayName', '395')
%scatter(data_395T_avg.exposureTime, data_395T_avg.imgMeanNorm, 'c', 'DisplayName', '395')
plot(data_395T_avg.exposureTime, orig1, '--m', [0 10e-3], xtnd1, '--m', 'DisplayName', '395')
theString = sprintf('395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (1-5*0.05), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
errorbar(data_798T_avg.exposureTime, data_798T_avg.imgMeanNorm, data_798T_avg.imgSTDNorm, '--k', 'DisplayName', '798')
%scatter(data_798T_avg.exposureTime, data_798T_avg.imgMeanNorm, 'm', 'DisplayName', '798')
plot(data_798T_avg.exposureTime, orig2,'--k', [0 5e-3], xtnd2, '--k', 'DisplayName', '798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (1-6*0.05), theString, 'FontSize', 12);
title('DN vs. Exposure Time (s) : Sensor Array (Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend

hold off



% NON-NORMALIZED ---- CHANNELS
figure(3)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.rMean, 'r', 'DisplayName', 'r55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'r55')
theString = sprintf('55r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-1*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.gMean, 'g', 'DisplayName', 'g55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'g55')
theString = sprintf('55g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-2*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.bMean, 'b', 'DisplayName', 'b55')
plot(data_55T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'b55')
theString = sprintf('55b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-3*0.005), theString, 'FontSize', 12);


% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.rMean, 'r', 'DisplayName', 'r99')
plot(data_99T_avg.exposureTime, orig1, 'r', [0 60e-3], xtnd1, 'r', 'DisplayName', 'r99')
theString = sprintf('99r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-4*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.gMean, 'g', 'DisplayName', 'g99')
plot(data_99T_avg.exposureTime, orig1, 'g', [0 60e-3], xtnd1, 'g', 'DisplayName', 'g99')
theString = sprintf('99g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-5*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.bMean, 'b', 'DisplayName', 'b99')
plot(data_99T_avg.exposureTime, orig1, 'b', [0 60e-3], xtnd1, 'b', 'DisplayName', 'b99')
theString = sprintf('99b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-6*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.rMean, 'r', 'DisplayName', 'r198')
plot(data_198T_avg.exposureTime, orig1, '-.r', [0 20e-3], xtnd1, '-.r', 'DisplayName', 'r198')
theString = sprintf('198r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-7*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.gMean, 'g', 'DisplayName', 'g198')
plot(data_198T_avg.exposureTime, orig1, '-.g', [0 20e-3], xtnd1, '-.g', 'DisplayName', 'g198')
theString = sprintf('198g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-8*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.bMean, 'b', 'DisplayName', 'b198')
plot(data_198T_avg.exposureTime, orig1, '-.b', [0 20e-3], xtnd1, '-.b', 'DisplayName', 'b198')
theString = sprintf('198b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-9*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.rMean, 'r', 'DisplayName', 'r299')
plot(data_299T_avg.exposureTime, orig1, ':r', [0 15e-3], xtnd1, ':r', 'DisplayName', 'r299')
theString = sprintf('299r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-10*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.gMean, 'g', 'DisplayName', 'g299')
plot(data_299T_avg.exposureTime, orig1, ':g', [0 15e-3], xtnd1, ':g', 'DisplayName', 'g299')
theString = sprintf('299g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-11*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.bMean, 'b', 'DisplayName', 'b299')
plot(data_299T_avg.exposureTime, orig1, ':b', [0 15e-3], xtnd1, ':b', 'DisplayName', 'b299')
theString = sprintf('299b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-12*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.rMean, 'c', 'DisplayName', 'r395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', 'r395')
theString = sprintf('395r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-13*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.gMean, 'm', 'DisplayName', 'g395')
plot(data_395T_avg.exposureTime, orig1, '--m', [0 10e-3], xtnd1, '--m', 'DisplayName', 'g395')
theString = sprintf('395g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-14*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.bMean, 'k', 'DisplayName', 'b395')
plot(data_395T_avg.exposureTime, orig1, '--k', [0 10e-3], xtnd1, '--k', 'DisplayName', 'b395')
theString = sprintf('395b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64.05-15*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.rMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.rMean, 'c', 'DisplayName', 'r798')
plot(data_798T_avg.exposureTime, orig2,'c', [0 5e-3], xtnd2, 'c', 'DisplayName', 'r798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798r: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (64.05-16*0.005), theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.gMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.gMean, 'm', 'DisplayName', 'g798')
plot(data_798T_avg.exposureTime, orig2,'m', [0 5e-3], xtnd2, 'm', 'DisplayName', 'g798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798g: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (64.05-17*0.005), theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.bMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.bMean, 'k', 'DisplayName', 'b798')
plot(data_798T_avg.exposureTime, orig2,'k', [0 5e-3], xtnd2, 'k', 'DisplayName', 'b798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798b: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (64.05-18*0.005), theString, 'FontSize', 12);

title('DN vs. Exposure Time (s) : Sensor Channels (Not Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off

% NORMALIZED ------ CHANNELS
figure(4)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.rMeanNorm, 'r', 'DisplayName', 'r55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'r55')
theString = sprintf('55r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-1*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.gMeanNorm, 'g', 'DisplayName', 'g55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'g55')
theString = sprintf('55g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-2*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.bMeanNorm, 'b', 'DisplayName', 'b55')
plot(data_55T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'b55')
theString = sprintf('55b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-3*0.0001), theString, 'FontSize', 12);


% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.rMeanNorm, 'r', 'DisplayName', 'r99')
plot(data_99T_avg.exposureTime, orig1, 'r', [0 60e-3], xtnd1, 'r', 'DisplayName', 'r99')
theString = sprintf('99r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-4*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.gMeanNorm, 'g', 'DisplayName', 'g99')
plot(data_99T_avg.exposureTime, orig1, 'g', [0 60e-3], xtnd1, 'g', 'DisplayName', 'g99')
theString = sprintf('99g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-5*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.bMeanNorm, 'b', 'DisplayName', 'b99')
plot(data_99T_avg.exposureTime, orig1, 'b', [0 60e-3], xtnd1, 'b', 'DisplayName', 'b99')
theString = sprintf('99b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-6*0.0001), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.rMeanNorm, 'r', 'DisplayName', 'r198')
plot(data_198T_avg.exposureTime, orig1, '-.r', [0 20e-3], xtnd1, '-.r', 'DisplayName', 'r198')
theString = sprintf('198r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-7*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.gMeanNorm, 'g', 'DisplayName', 'g198')
plot(data_198T_avg.exposureTime, orig1, '-.g', [0 20e-3], xtnd1, '-.g', 'DisplayName', 'g198')
theString = sprintf('198g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-8*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.bMeanNorm, 'b', 'DisplayName', 'b198')
plot(data_198T_avg.exposureTime, orig1, '-.b', [0 20e-3], xtnd1, '-.b', 'DisplayName', 'b198')
theString = sprintf('198b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-9*0.0001), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.rMeanNorm, 'r', 'DisplayName', 'r299')
plot(data_299T_avg.exposureTime, orig1, ':r', [0 15e-3], xtnd1, ':r', 'DisplayName', 'r299')
theString = sprintf('299r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-10*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.gMeanNorm, 'g', 'DisplayName', 'g299')
plot(data_299T_avg.exposureTime, orig1, ':g', [0 15e-3], xtnd1, ':g', 'DisplayName', 'g299')
theString = sprintf('299g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-11*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.bMeanNorm, 'b', 'DisplayName', 'b299')
plot(data_299T_avg.exposureTime, orig1, ':b', [0 15e-3], xtnd1, ':b', 'DisplayName', 'b299')
theString = sprintf('299b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-12*0.0001), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.rMeanNorm, 'c', 'DisplayName', 'r395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', 'r395')
theString = sprintf('395r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-13*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.gMeanNorm, 'm', 'DisplayName', 'g395')
plot(data_395T_avg.exposureTime, orig1, '--m', [0 10e-3], xtnd1, '--m', 'DisplayName', 'g395')
theString = sprintf('395g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-14*0.0001), theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.bMeanNorm, 'k', 'DisplayName', 'b395')
plot(data_395T_avg.exposureTime, orig1, '--k', [0 10e-3], xtnd1, '--k', 'DisplayName', 'b395')
theString = sprintf('395b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (3e-3-15*0.0001), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.rMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.rMeanNorm, 'c', 'DisplayName', 'r798')
plot(data_798T_avg.exposureTime, orig2,'--c', [0 5e-3], xtnd2, '--c', 'DisplayName', 'r798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798r: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (3e-3-16*0.0001), theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.gMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.gMeanNorm, 'm', 'DisplayName', 'g798')
plot(data_798T_avg.exposureTime, orig2,'--m', [0 5e-3], xtnd2, '--m', 'DisplayName', 'g798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798g: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (3e-3-17*0.0001), theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.bMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.bMeanNorm, 'k', 'DisplayName', 'b798')
plot(data_798T_avg.exposureTime, orig2,'--k', [0 5e-3], xtnd2, '--k', 'DisplayName', 'b798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798b: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (3e-3-18*0.0001), theString, 'FontSize', 12);

title('DN vs. Exposure Time (s) : Sensor Channels (Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off



% NON-NORMALIZED ---- SENSOR LOCATION
figure(5)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.imgTLmean, 'r', 'DisplayName', 'TL55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'TL55')
theString = sprintf('TL55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 64, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.imgMmean, 'g', 'DisplayName', 'M55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'M55')
theString = sprintf('M55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-1*0.005), theString, 'FontSize', 12);




% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.imgTLmean, 'b', 'DisplayName', 'TL99')
plot(data_99T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'TL99')
theString = sprintf('TL99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-2*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.imgMmean, 'c', 'DisplayName', 'M99')
plot(data_99T_avg.exposureTime, orig1, '--c', [0 60e-3], xtnd1, '--c', 'DisplayName', 'M99')
theString = sprintf('M99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-3*0.005), theString, 'FontSize', 12);


% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.imgTLmean, 'm', 'DisplayName', 'TL198')
plot(data_198T_avg.exposureTime, orig1, '--m', [0 20e-3], xtnd1, '--m', 'DisplayName', 'TL198')
theString = sprintf('TL198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-4*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.imgMmean, 'k', 'DisplayName', 'M198')
plot(data_198T_avg.exposureTime, orig1, '--k', [0 20e-3], xtnd1, '--k', 'DisplayName', 'M198')
theString = sprintf('M198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-5*0.005), theString, 'FontSize', 12);


% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.imgTLmean, 'r', 'DisplayName', 'TL299')
plot(data_299T_avg.exposureTime, orig1, 'r', [0 15e-3], xtnd1, 'r', 'DisplayName', 'TL299')
theString = sprintf('TL299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-6*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.imgMmean, 'g', 'DisplayName', 'M299')
plot(data_299T_avg.exposureTime, orig1, 'g', [0 15e-3], xtnd1, 'g', 'DisplayName', 'M299')
theString = sprintf('M299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-7*0.005), theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.imgTLmean, 'b', 'DisplayName', 'TL395')
plot(data_395T_avg.exposureTime, orig1, 'b', [0 10e-3], xtnd1, 'b', 'DisplayName', 'TL395')
theString = sprintf('TL395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-8*0.005), theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.imgMmean, 'c', 'DisplayName', 'M395')
plot(data_395T_avg.exposureTime, orig1, 'c', [0 10e-3], xtnd1, 'c', 'DisplayName', 'M395')
theString = sprintf('M395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, (64-9*0.005), theString, 'FontSize', 12);


% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgTLmean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.imgTLmean, 'm', 'DisplayName', 'TL798')
plot(data_798T_avg.exposureTime, orig2,'m', [0 5e-3], xtnd2, 'm', 'DisplayName', 'TL798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('TL798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (64-10*0.005), theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMmean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.imgMmean, 'r', 'DisplayName', 'M798')
plot(data_798T_avg.exposureTime, orig2,'-.r', [0 5e-3], xtnd2, '-.r', 'DisplayName', 'M798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('M798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, (64-11*0.005), theString, 'FontSize', 12);


title('DN vs. Exposure Time (s) : Sensor Location (Not Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off



% NORMALIZED ---- SENSOR LOCATION
figure(6)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
errorbar(data_55T_avg.exposureTime, data_55T_avg.imgTLmeanNorm, data_55T_avg.imgTLstdNorm, '--r', 'DisplayName', 'TL55')
%scatter(data_55T_avg.exposureTime, data_55T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'TL55')
theString = sprintf('TL55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 1.5, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
errorbar(data_55T_avg.exposureTime, data_55T_avg.imgMmeanNorm, data_55T_avg.imgMstdNorm, '--g', 'DisplayName', 'M55')
%scatter(data_55T_avg.exposureTime, data_55T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'M55')
theString = sprintf('M55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 1.4, theString, 'FontSize', 12);




% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
errorbar(data_99T_avg.exposureTime, data_99T_avg.imgTLmeanNorm, data_99T_avg.imgTLstdNorm, '--b', 'DisplayName', 'TL99')
%scatter(data_99T_avg.exposureTime, data_99T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL99')
plot(data_99T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'TL99')
theString = sprintf('TL99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 1.3, theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
errorbar(data_99T_avg.exposureTime, data_99T_avg.imgMmeanNorm, data_99T_avg.imgMstdNorm, 'r', 'DisplayName', 'M99')
%scatter(data_99T_avg.exposureTime, data_99T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M99')
plot(data_99T_avg.exposureTime, orig1, 'r', [0 60e-3], xtnd1, 'r', 'DisplayName', 'M99')
theString = sprintf('M99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 1.2, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
errorbar(data_198T_avg.exposureTime, data_198T_avg.imgTLmeanNorm, data_198T_avg.imgTLstdNorm, 'g', 'DisplayName', 'TL198')
%scatter(data_198T_avg.exposureTime, data_198T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL198')
plot(data_198T_avg.exposureTime, orig1, 'g', [0 20e-3], xtnd1, 'g', 'DisplayName', 'TL198')
theString = sprintf('TL198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 1.1, theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
errorbar(data_198T_avg.exposureTime, data_198T_avg.imgMmeanNorm, data_198T_avg.imgMstdNorm, 'b',  'DisplayName', 'M198')
%scatter(data_198T_avg.exposureTime, data_198T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M198')
plot(data_198T_avg.exposureTime, orig1, 'b', [0 20e-3], xtnd1, 'b', 'DisplayName', 'M198')
theString = sprintf('M198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 1, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
errorbar(data_299T_avg.exposureTime, data_299T_avg.imgTLmeanNorm, data_299T_avg.imgTLstdNorm, '-.r', 'DisplayName', 'TL299')
%scatter(data_299T_avg.exposureTime, data_299T_avg.imgTLmeanNorm, 'b', 'DisplayName', 'TL299')
plot(data_299T_avg.exposureTime, orig1, '-.r', [0 15e-3], xtnd1, '-.r', 'DisplayName', 'TL299')
theString = sprintf('TL299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 0.9, theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
errorbar(data_299T_avg.exposureTime, data_299T_avg.imgMmeanNorm, data_299T_avg.imgMstdNorm,'-.g', 'DisplayName', 'M299')
%scatter(data_299T_avg.exposureTime, data_299T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M299')
plot(data_299T_avg.exposureTime, orig1, '-.g', [0 15e-3], xtnd1, '-.g', 'DisplayName', 'M299')
theString = sprintf('M299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 0.8, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
errorbar(data_395T_avg.exposureTime, data_395T_avg.imgTLmeanNorm, data_395T_avg.imgTLstdNorm, '-.b', 'DisplayName', 'TL395')
%scatter(data_395T_avg.exposureTime, data_395T_avg.imgTLmeanNorm, 'b', 'DisplayName', 'TL395')
plot(data_395T_avg.exposureTime, orig1, '-.b', [0 10e-3], xtnd1, '-.b', 'DisplayName', 'TL395')
theString = sprintf('TL395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 0.7, theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
errorbar(data_395T_avg.exposureTime, data_395T_avg.imgMmeanNorm, data_395T_avg.imgMstdNorm, '--c', 'DisplayName', 'M395')
%scatter(data_395T_avg.exposureTime, data_395T_avg.imgMmeanNorm, 'c', 'DisplayName', 'M395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', 'M395')
theString = sprintf('M395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(100e-3, 0.6, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgTLmeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
errorbar(data_798T_avg.exposureTime, data_798T_avg.imgTLmeanNorm, data_798T_avg.imgTLstdNorm,'--m', 'DisplayName', 'TL798')
%scatter(data_798T_avg.exposureTime, data_798T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL798')
plot(data_798T_avg.exposureTime, orig2,'--m', [0 5e-3], xtnd2, '--m', 'DisplayName', 'TL798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('TL798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, 0.5, theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMmeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
errorbar(data_798T_avg.exposureTime, data_798T_avg.imgMmeanNorm, data_798T_avg.imgMstdNorm, '--k',  'DisplayName', 'M798')
%scatter(data_798T_avg.exposureTime, data_798T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M798')
plot(data_798T_avg.exposureTime, orig2,'--k', [0 5e-3], xtnd2, '--k', 'DisplayName', 'M798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('M798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(100e-3, 0.4, theString, 'FontSize', 12);


title('DN vs. Exposure Time (s) : Sensor Location (Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off