%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PSYCH 221 : Google Pixel 4A Noise Model - Read Noise Estimation
% Authors : Melissa Horowitz, Joey Yurgelon
% Date : 11/3/2020
% Required File Structure : 
%          See 'project/README.txt' - MATLAB
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Load in the specific structure generated by the GenerateDataStructures
% script. This takes a long time. Load it in and then manipulate the data.

close all
clear all
clc

%load('Z:\PRNU_DSNU_Data')
load('PRNU_DSNU_Data')

%% Manipulation of the data. If images have not been averaged.

T = struct2table(data_55S); % convert the struct array to a table
data_55T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_99S); % convert the struct array to a table
data_99T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_198S); % convert the struct array to a table
data_198T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_299S); % convert the struct array to a table
data_299T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_395S); % convert the struct array to a table
data_395T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'
T = struct2table(data_798S); % convert the struct array to a table
data_798T = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

 j = 1;
 for i = 1:5:length(data_55T.exposureTime)
     x1 = data_55S(i);
     x2 = data_55S(i+1);
     x3 = data_55S(i+2);
     x4 = data_55S(i+3);
     x5 = data_55S(i+4);
     
     data_55S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_55S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_55S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_55S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     
     
     data_55S_avg(j).rMean = (x1.rMean + x2.rMean + x3.rMean + x4.rMean  + x5.rMean)/5;
     data_55S_avg(j).gMean = (x1.gMean + x2.gMean + x3.gMean + x4.gMean  + x5.gMean)/5;
     data_55S_avg(j).bMean = (x1.bMean + x2.bMean + x3.bMean + x4.bMean  + x5.bMean)/5;
     
     
     data_55S_avg(j).rMeanNorm = (x1.rMeanNorm + x2.rMeanNorm + x3.rMeanNorm + x4.rMeanNorm  + x5.rMeanNorm)/5;
     data_55S_avg(j).gMeanNorm = (x1.gMeanNorm + x2.gMeanNorm + x3.gMeanNorm + x4.gMeanNorm  + x5.gMeanNorm)/5;
     data_55S_avg(j).bMeanNorm = (x1.bMeanNorm + x2.bMeanNorm + x3.bMeanNorm + x4.bMeanNorm  + x5.bMeanNorm)/5;
     
     data_55S_avg(j).imgTLmean = (x1.imgTLmean + x2.imgTLmean + x3.imgTLmean + x4.imgTLmean  + x5.imgTLmean)/5;
     data_55S_avg(j).imgTMmean = (x1.imgTMmean  + x2.imgTMmean  + x3.imgTMmean  + x4.imgTMmean   + x5.imgTMmean )/5;
     data_55S_avg(j).imgLMmean = (x1.imgLMmean + x2.imgLMmean + x3.imgLMmean + x4.imgLMmean  + x5.imgLMmean)/5;
     data_55S_avg(j).imgMmean = (x1.imgMmean + x2.imgMmean + x3.imgMmean + x4.imgMmean  + x5.imgMmean)/5;

     data_55S_avg(j).imgTLmeanNorm = (x1.imgTLmeanNorm + x2.imgTLmeanNorm + x3.imgTLmeanNorm + x4.imgTLmeanNorm  + x5.imgTLmeanNorm)/5;
     data_55S_avg(j).imgTMmeanNorm = (x1.imgTMmeanNorm  + x2.imgTMmeanNorm  + x3.imgTMmeanNorm  + x4.imgTMmeanNorm   + x5.imgTMmeanNorm )/5;
     data_55S_avg(j).imgLMmeanNorm = (x1.imgLMmeanNorm + x2.imgLMmeanNorm + x3.imgLMmeanNorm + x4.imgLMmeanNorm  + x5.imgLMmeanNorm)/5;
     data_55S_avg(j).imgMmeanNorm = (x1.imgMmeanNorm + x2.imgMmeanNorm + x3.imgMmeanNorm + x4.imgMmeanNorm  + x5.imgMmeanNorm)/5;

     data_55S_avg(j).imgSTD = (x1.imgSTD + x2.imgSTD + x3.imgSTD + x4.imgSTD  + x5.imgSTD)/5;
     data_55S_avg(j).imgSTDNorm = (x1.imgSTDNorm + x2.imgSTDNorm + x3.imgSTDNorm + x4.imgSTDNorm  + x5.imgSTDNorm)/5;
     
     data_55S_avg(j).rSTD = (x1.rSTD + x2.rSTD + x3.rSTD + x4.rSTD  + x5.rSTD)/5;
     data_55S_avg(j).gSTD = (x1.gSTD + x2.gSTD + x3.gSTD + x4.gSTD  + x5.gSTD)/5;
     data_55S_avg(j).bSTD = (x1.bSTD + x2.bSTD + x3.bSTD + x4.bSTD  + x5.bSTD)/5;
     data_55S_avg(j).rSTDNorm = (x1.rSTDNorm + x2.rSTDNorm + x3.rSTDNorm + x4.rSTDNorm  + x5.rSTDNorm)/5;
     data_55S_avg(j).gSTDNorm = (x1.gSTDNorm + x2.gSTDNorm + x3.gSTDNorm + x4.gSTDNorm  + x5.gSTDNorm)/5;
     data_55S_avg(j).bSTDNorm = (x1.bSTDNorm + x2.bSTDNorm + x3.bSTDNorm + x4.bSTDNorm  + x5.bSTDNorm)/5;
     
     data_55S_avg(j).imgTLstd = (x1.imgTLstd + x2.imgTLstd + x3.imgTLstd + x4.imgTLstd  + x5.imgTLstd)/5;
     data_55S_avg(j).imgTMstd = (x1.imgTMstd  + x2.imgTMstd  + x3.imgTMstd  + x4.imgTMstd   + x5.imgTMstd)/5;
     data_55S_avg(j).imgLMstd = (x1.imgLMstd + x2.imgLMstd + x3.imgLMstd + x4.imgLMstd  + x5.imgLMstd)/5;
     data_55S_avg(j).imgMstd = (x1.imgMstd + x2.imgMstd + x3.imgMstd + x4.imgMstd  + x5.imgMstd)/5;

     data_55S_avg(j).imgTLstdNorm = (x1.imgTLstdNorm + x2.imgTLstdNorm + x3.imgTLstdNorm + x4.imgTLstdNorm  + x5.imgTLstdNorm)/5;
     data_55S_avg(j).imgTMstdNorm = (x1.imgTMstdNorm  + x2.imgTMstdNorm  + x3.imgTMstdNorm  + x4.imgTMstdNorm   + x5.imgTMstdNorm )/5;
     data_55S_avg(j).imgLMstdNorm = (x1.imgLMstdNorm + x2.imgLMstdNorm + x3.imgLMstdNorm + x4.imgLMstdNorm  + x5.imgLMstdNorm)/5;
     data_55S_avg(j).imgMstdNorm = (x1.imgMstdNorm + x2.imgMstdNorm + x3.imgMstdNorm + x4.imgMstdNorm  + x5.imgMstdNorm)/5;
     
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_99T.exposureTime)
     x1 = data_99S(i);
     x2 = data_99S(i+1);
     x3 = data_99S(i+2);
     x4 = data_99S(i+3);
     x5 = data_99S(i+4);
     
     data_99S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_99S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_99S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_99S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     
     data_99S_avg(j).rMean = (x1.rMean + x2.rMean + x3.rMean + x4.rMean  + x5.rMean)/5;
     data_99S_avg(j).gMean = (x1.gMean + x2.gMean + x3.gMean + x4.gMean  + x5.gMean)/5;
     data_99S_avg(j).bMean = (x1.bMean + x2.bMean + x3.bMean + x4.bMean  + x5.bMean)/5;     

     data_99S_avg(j).rMeanNorm = (x1.rMeanNorm + x2.rMeanNorm + x3.rMeanNorm + x4.rMeanNorm  + x5.rMeanNorm)/5;
     data_99S_avg(j).gMeanNorm = (x1.gMeanNorm + x2.gMeanNorm + x3.gMeanNorm + x4.gMeanNorm  + x5.gMeanNorm)/5;
     data_99S_avg(j).bMeanNorm = (x1.bMeanNorm + x2.bMeanNorm + x3.bMeanNorm + x4.bMeanNorm  + x5.bMeanNorm)/5;
     
     data_99S_avg(j).imgTLmean = (x1.imgTLmean + x2.imgTLmean + x3.imgTLmean + x4.imgTLmean  + x5.imgTLmean)/5;
     data_99S_avg(j).imgTMmean = (x1.imgTMmean  + x2.imgTMmean  + x3.imgTMmean  + x4.imgTMmean   + x5.imgTMmean )/5;
     data_99S_avg(j).imgLMmean = (x1.imgLMmean + x2.imgLMmean + x3.imgLMmean + x4.imgLMmean  + x5.imgLMmean)/5;
     data_99S_avg(j).imgMmean = (x1.imgMmean + x2.imgMmean + x3.imgMmean + x4.imgMmean  + x5.imgMmean)/5;
     
     data_99S_avg(j).imgTLmeanNorm = (x1.imgTLmeanNorm + x2.imgTLmeanNorm + x3.imgTLmeanNorm + x4.imgTLmeanNorm  + x5.imgTLmeanNorm)/5;
     data_99S_avg(j).imgTMmeanNorm = (x1.imgTMmeanNorm  + x2.imgTMmeanNorm  + x3.imgTMmeanNorm  + x4.imgTMmeanNorm   + x5.imgTMmeanNorm )/5;
     data_99S_avg(j).imgLMmeanNorm = (x1.imgLMmeanNorm + x2.imgLMmeanNorm + x3.imgLMmeanNorm + x4.imgLMmeanNorm  + x5.imgLMmeanNorm)/5;
     data_99S_avg(j).imgMmeanNorm = (x1.imgMmeanNorm + x2.imgMmeanNorm + x3.imgMmeanNorm + x4.imgMmeanNorm  + x5.imgMmeanNorm)/5;     
     
     data_99S_avg(j).imgSTD = (x1.imgSTD + x2.imgSTD + x3.imgSTD + x4.imgSTD  + x5.imgSTD)/5;
     data_99S_avg(j).imgSTDNorm = (x1.imgSTDNorm + x2.imgSTDNorm + x3.imgSTDNorm + x4.imgSTDNorm  + x5.imgSTDNorm)/5;
     
     data_99S_avg(j).rSTD = (x1.rSTD + x2.rSTD + x3.rSTD + x4.rSTD  + x5.rSTD)/5;
     data_99S_avg(j).gSTD = (x1.gSTD + x2.gSTD + x3.gSTD + x4.gSTD  + x5.gSTD)/5;
     data_99S_avg(j).bSTD = (x1.bSTD + x2.bSTD + x3.bSTD + x4.bSTD  + x5.bSTD)/5;
     data_99S_avg(j).rSTDNorm = (x1.rSTDNorm + x2.rSTDNorm + x3.rSTDNorm + x4.rSTDNorm  + x5.rSTDNorm)/5;
     data_99S_avg(j).gSTDNorm = (x1.gSTDNorm + x2.gSTDNorm + x3.gSTDNorm + x4.gSTDNorm  + x5.gSTDNorm)/5;
     data_99S_avg(j).bSTDNorm = (x1.bSTDNorm + x2.bSTDNorm + x3.bSTDNorm + x4.bSTDNorm  + x5.bSTDNorm)/5;
     
     data_99S_avg(j).imgTLstd = (x1.imgTLstd + x2.imgTLstd + x3.imgTLstd + x4.imgTLstd  + x5.imgTLstd)/5;
     data_99S_avg(j).imgTMstd = (x1.imgTMstd  + x2.imgTMstd  + x3.imgTMstd  + x4.imgTMstd   + x5.imgTMstd)/5;
     data_99S_avg(j).imgLMstd = (x1.imgLMstd + x2.imgLMstd + x3.imgLMstd + x4.imgLMstd  + x5.imgLMstd)/5;
     data_99S_avg(j).imgMstd = (x1.imgMstd + x2.imgMstd + x3.imgMstd + x4.imgMstd  + x5.imgMstd)/5;

     data_99S_avg(j).imgTLstdNorm = (x1.imgTLstdNorm + x2.imgTLstdNorm + x3.imgTLstdNorm + x4.imgTLstdNorm  + x5.imgTLstdNorm)/5;
     data_99S_avg(j).imgTMstdNorm = (x1.imgTMstdNorm  + x2.imgTMstdNorm  + x3.imgTMstdNorm  + x4.imgTMstdNorm   + x5.imgTMstdNorm )/5;
     data_99S_avg(j).imgLMstdNorm = (x1.imgLMstdNorm + x2.imgLMstdNorm + x3.imgLMstdNorm + x4.imgLMstdNorm  + x5.imgLMstdNorm)/5;
     data_99S_avg(j).imgMstdNorm = (x1.imgMstdNorm + x2.imgMstdNorm + x3.imgMstdNorm + x4.imgMstdNorm  + x5.imgMstdNorm)/5;
     
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_198T.exposureTime)
     x1 = data_198S(i);
     x2 = data_198S(i+1);
     x3 = data_198S(i+2);
     x4 = data_198S(i+3);
     x5 = data_198S(i+4);
     
     data_198S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_198S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_198S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_198S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     
     data_198S_avg(j).rMean = (x1.rMean + x2.rMean + x3.rMean + x4.rMean  + x5.rMean)/5;
     data_198S_avg(j).gMean = (x1.gMean + x2.gMean + x3.gMean + x4.gMean  + x5.gMean)/5;
     data_198S_avg(j).bMean = (x1.bMean + x2.bMean + x3.bMean + x4.bMean  + x5.bMean)/5;        
     
     data_198S_avg(j).rMeanNorm = (x1.rMeanNorm + x2.rMeanNorm + x3.rMeanNorm + x4.rMeanNorm  + x5.rMeanNorm)/5;
     data_198S_avg(j).gMeanNorm = (x1.gMeanNorm + x2.gMeanNorm + x3.gMeanNorm + x4.gMeanNorm  + x5.gMeanNorm)/5;
     data_198S_avg(j).bMeanNorm = (x1.bMeanNorm + x2.bMeanNorm + x3.bMeanNorm + x4.bMeanNorm  + x5.bMeanNorm)/5;
     
     data_198S_avg(j).imgTLmean = (x1.imgTLmean + x2.imgTLmean + x3.imgTLmean + x4.imgTLmean  + x5.imgTLmean)/5;
     data_198S_avg(j).imgTMmean = (x1.imgTMmean  + x2.imgTMmean  + x3.imgTMmean  + x4.imgTMmean   + x5.imgTMmean )/5;
     data_198S_avg(j).imgLMmean = (x1.imgLMmean + x2.imgLMmean + x3.imgLMmean + x4.imgLMmean  + x5.imgLMmean)/5;
     data_198S_avg(j).imgMmean = (x1.imgMmean + x2.imgMmean + x3.imgMmean + x4.imgMmean  + x5.imgMmean)/5;
     
     data_198S_avg(j).imgTLmeanNorm = (x1.imgTLmeanNorm + x2.imgTLmeanNorm + x3.imgTLmeanNorm + x4.imgTLmeanNorm  + x5.imgTLmeanNorm)/5;
     data_198S_avg(j).imgTMmeanNorm = (x1.imgTMmeanNorm  + x2.imgTMmeanNorm  + x3.imgTMmeanNorm  + x4.imgTMmeanNorm   + x5.imgTMmeanNorm )/5;
     data_198S_avg(j).imgLMmeanNorm = (x1.imgLMmeanNorm + x2.imgLMmeanNorm + x3.imgLMmeanNorm + x4.imgLMmeanNorm  + x5.imgLMmeanNorm)/5;
     data_198S_avg(j).imgMmeanNorm = (x1.imgMmeanNorm + x2.imgMmeanNorm + x3.imgMmeanNorm + x4.imgMmeanNorm  + x5.imgMmeanNorm)/5;     
     
     data_198S_avg(j).imgSTD = (x1.imgSTD + x2.imgSTD + x3.imgSTD + x4.imgSTD  + x5.imgSTD)/5;
     data_198S_avg(j).imgSTDNorm = (x1.imgSTDNorm + x2.imgSTDNorm + x3.imgSTDNorm + x4.imgSTDNorm  + x5.imgSTDNorm)/5;
     
     data_198S_avg(j).rSTD = (x1.rSTD + x2.rSTD + x3.rSTD + x4.rSTD  + x5.rSTD)/5;
     data_198S_avg(j).gSTD = (x1.gSTD + x2.gSTD + x3.gSTD + x4.gSTD  + x5.gSTD)/5;
     data_198S_avg(j).bSTD = (x1.bSTD + x2.bSTD + x3.bSTD + x4.bSTD  + x5.bSTD)/5;
     data_198S_avg(j).rSTDNorm = (x1.rSTDNorm + x2.rSTDNorm + x3.rSTDNorm + x4.rSTDNorm  + x5.rSTDNorm)/5;
     data_198S_avg(j).gSTDNorm = (x1.gSTDNorm + x2.gSTDNorm + x3.gSTDNorm + x4.gSTDNorm  + x5.gSTDNorm)/5;
     data_198S_avg(j).bSTDNorm = (x1.bSTDNorm + x2.bSTDNorm + x3.bSTDNorm + x4.bSTDNorm  + x5.bSTDNorm)/5;
     
     data_198S_avg(j).imgTLstd = (x1.imgTLstd + x2.imgTLstd + x3.imgTLstd + x4.imgTLstd  + x5.imgTLstd)/5;
     data_198S_avg(j).imgTMstd = (x1.imgTMstd  + x2.imgTMstd  + x3.imgTMstd  + x4.imgTMstd   + x5.imgTMstd)/5;
     data_198S_avg(j).imgLMstd = (x1.imgLMstd + x2.imgLMstd + x3.imgLMstd + x4.imgLMstd  + x5.imgLMstd)/5;
     data_198S_avg(j).imgMstd = (x1.imgMstd + x2.imgMstd + x3.imgMstd + x4.imgMstd  + x5.imgMstd)/5;

     data_198S_avg(j).imgTLstdNorm = (x1.imgTLstdNorm + x2.imgTLstdNorm + x3.imgTLstdNorm + x4.imgTLstdNorm  + x5.imgTLstdNorm)/5;
     data_198S_avg(j).imgTMstdNorm = (x1.imgTMstdNorm  + x2.imgTMstdNorm  + x3.imgTMstdNorm  + x4.imgTMstdNorm   + x5.imgTMstdNorm )/5;
     data_198S_avg(j).imgLMstdNorm = (x1.imgLMstdNorm + x2.imgLMstdNorm + x3.imgLMstdNorm + x4.imgLMstdNorm  + x5.imgLMstdNorm)/5;
     data_198S_avg(j).imgMstdNorm = (x1.imgMstdNorm + x2.imgMstdNorm + x3.imgMstdNorm + x4.imgMstdNorm  + x5.imgMstdNorm)/5;
     
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_299T.exposureTime)
     x1 = data_299S(i);
     x2 = data_299S(i+1);
     x3 = data_299S(i+2);
     x4 = data_299S(i+3);
     x5 = data_299S(i+4);
     
     data_299S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_299S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_299S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_299S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     
     data_299S_avg(j).rMean = (x1.rMean + x2.rMean + x3.rMean + x4.rMean  + x5.rMean)/5;
     data_299S_avg(j).gMean = (x1.gMean + x2.gMean + x3.gMean + x4.gMean  + x5.gMean)/5;
     data_299S_avg(j).bMean = (x1.bMean + x2.bMean + x3.bMean + x4.bMean  + x5.bMean)/5;           
     
     data_299S_avg(j).rMeanNorm = (x1.rMeanNorm + x2.rMeanNorm + x3.rMeanNorm + x4.rMeanNorm  + x5.rMeanNorm)/5;
     data_299S_avg(j).gMeanNorm = (x1.gMeanNorm + x2.gMeanNorm + x3.gMeanNorm + x4.gMeanNorm  + x5.gMeanNorm)/5;
     data_299S_avg(j).bMeanNorm = (x1.bMeanNorm + x2.bMeanNorm + x3.bMeanNorm + x4.bMeanNorm  + x5.bMeanNorm)/5;
     
     data_299S_avg(j).imgTLmean = (x1.imgTLmean + x2.imgTLmean + x3.imgTLmean + x4.imgTLmean  + x5.imgTLmean)/5;
     data_299S_avg(j).imgTMmean = (x1.imgTMmean  + x2.imgTMmean  + x3.imgTMmean  + x4.imgTMmean   + x5.imgTMmean )/5;
     data_299S_avg(j).imgLMmean = (x1.imgLMmean + x2.imgLMmean + x3.imgLMmean + x4.imgLMmean  + x5.imgLMmean)/5;
     data_299S_avg(j).imgMmean = (x1.imgMmean + x2.imgMmean + x3.imgMmean + x4.imgMmean  + x5.imgMmean)/5;
     
     data_299S_avg(j).imgTLmeanNorm = (x1.imgTLmeanNorm + x2.imgTLmeanNorm + x3.imgTLmeanNorm + x4.imgTLmeanNorm  + x5.imgTLmeanNorm)/5;
     data_299S_avg(j).imgTMmeanNorm = (x1.imgTMmeanNorm  + x2.imgTMmeanNorm  + x3.imgTMmeanNorm  + x4.imgTMmeanNorm   + x5.imgTMmeanNorm )/5;
     data_299S_avg(j).imgLMmeanNorm = (x1.imgLMmeanNorm + x2.imgLMmeanNorm + x3.imgLMmeanNorm + x4.imgLMmeanNorm  + x5.imgLMmeanNorm)/5;
     data_299S_avg(j).imgMmeanNorm = (x1.imgMmeanNorm + x2.imgMmeanNorm + x3.imgMmeanNorm + x4.imgMmeanNorm  + x5.imgMmeanNorm)/5;     
     
     data_299S_avg(j).imgSTD = (x1.imgSTD + x2.imgSTD + x3.imgSTD + x4.imgSTD  + x5.imgSTD)/5;
     data_299S_avg(j).imgSTDNorm = (x1.imgSTDNorm + x2.imgSTDNorm + x3.imgSTDNorm + x4.imgSTDNorm  + x5.imgSTDNorm)/5;
     
     data_299S_avg(j).rSTD = (x1.rSTD + x2.rSTD + x3.rSTD + x4.rSTD  + x5.rSTD)/5;
     data_299S_avg(j).gSTD = (x1.gSTD + x2.gSTD + x3.gSTD + x4.gSTD  + x5.gSTD)/5;
     data_299S_avg(j).bSTD = (x1.bSTD + x2.bSTD + x3.bSTD + x4.bSTD  + x5.bSTD)/5;
     data_299S_avg(j).rSTDNorm = (x1.rSTDNorm + x2.rSTDNorm + x3.rSTDNorm + x4.rSTDNorm  + x5.rSTDNorm)/5;
     data_299S_avg(j).gSTDNorm = (x1.gSTDNorm + x2.gSTDNorm + x3.gSTDNorm + x4.gSTDNorm  + x5.gSTDNorm)/5;
     data_299S_avg(j).bSTDNorm = (x1.bSTDNorm + x2.bSTDNorm + x3.bSTDNorm + x4.bSTDNorm  + x5.bSTDNorm)/5;
     
     data_299S_avg(j).imgTLstd = (x1.imgTLstd + x2.imgTLstd + x3.imgTLstd + x4.imgTLstd  + x5.imgTLstd)/5;
     data_299S_avg(j).imgTMstd = (x1.imgTMstd  + x2.imgTMstd  + x3.imgTMstd  + x4.imgTMstd   + x5.imgTMstd)/5;
     data_299S_avg(j).imgLMstd = (x1.imgLMstd + x2.imgLMstd + x3.imgLMstd + x4.imgLMstd  + x5.imgLMstd)/5;
     data_299S_avg(j).imgMstd = (x1.imgMstd + x2.imgMstd + x3.imgMstd + x4.imgMstd  + x5.imgMstd)/5;

     data_299S_avg(j).imgTLstdNorm = (x1.imgTLstdNorm + x2.imgTLstdNorm + x3.imgTLstdNorm + x4.imgTLstdNorm  + x5.imgTLstdNorm)/5;
     data_299S_avg(j).imgTMstdNorm = (x1.imgTMstdNorm  + x2.imgTMstdNorm  + x3.imgTMstdNorm  + x4.imgTMstdNorm   + x5.imgTMstdNorm )/5;
     data_299S_avg(j).imgLMstdNorm = (x1.imgLMstdNorm + x2.imgLMstdNorm + x3.imgLMstdNorm + x4.imgLMstdNorm  + x5.imgLMstdNorm)/5;
     data_299S_avg(j).imgMstdNorm = (x1.imgMstdNorm + x2.imgMstdNorm + x3.imgMstdNorm + x4.imgMstdNorm  + x5.imgMstdNorm)/5;
     
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_395T.exposureTime)
     x1 = data_395S(i);
     x2 = data_395S(i+1);
     x3 = data_395S(i+2);
     x4 = data_395S(i+3);
     x5 = data_395S(i+4);
     
     data_395S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_395S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_395S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_395S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     
     data_395S_avg(j).rMean = (x1.rMean + x2.rMean + x3.rMean + x4.rMean  + x5.rMean)/5;
     data_395S_avg(j).gMean = (x1.gMean + x2.gMean + x3.gMean + x4.gMean  + x5.gMean)/5;
     data_395S_avg(j).bMean = (x1.bMean + x2.bMean + x3.bMean + x4.bMean  + x5.bMean)/5;         
     
     data_395S_avg(j).rMeanNorm = (x1.rMeanNorm + x2.rMeanNorm + x3.rMeanNorm + x4.rMeanNorm  + x5.rMeanNorm)/5;
     data_395S_avg(j).gMeanNorm = (x1.gMeanNorm + x2.gMeanNorm + x3.gMeanNorm + x4.gMeanNorm  + x5.gMeanNorm)/5;
     data_395S_avg(j).bMeanNorm = (x1.bMeanNorm + x2.bMeanNorm + x3.bMeanNorm + x4.bMeanNorm  + x5.bMeanNorm)/5;
     
     data_395S_avg(j).imgTLmean = (x1.imgTLmean + x2.imgTLmean + x3.imgTLmean + x4.imgTLmean  + x5.imgTLmean)/5;
     data_395S_avg(j).imgTMmean = (x1.imgTMmean  + x2.imgTMmean  + x3.imgTMmean  + x4.imgTMmean   + x5.imgTMmean )/5;
     data_395S_avg(j).imgLMmean = (x1.imgLMmean + x2.imgLMmean + x3.imgLMmean + x4.imgLMmean  + x5.imgLMmean)/5;
     data_395S_avg(j).imgMmean = (x1.imgMmean + x2.imgMmean + x3.imgMmean + x4.imgMmean  + x5.imgMmean)/5;
     
     data_395S_avg(j).imgTLmeanNorm = (x1.imgTLmeanNorm + x2.imgTLmeanNorm + x3.imgTLmeanNorm + x4.imgTLmeanNorm  + x5.imgTLmeanNorm)/5;
     data_395S_avg(j).imgTMmeanNorm = (x1.imgTMmeanNorm  + x2.imgTMmeanNorm  + x3.imgTMmeanNorm  + x4.imgTMmeanNorm   + x5.imgTMmeanNorm )/5;
     data_395S_avg(j).imgLMmeanNorm = (x1.imgLMmeanNorm + x2.imgLMmeanNorm + x3.imgLMmeanNorm + x4.imgLMmeanNorm  + x5.imgLMmeanNorm)/5;
     data_395S_avg(j).imgMmeanNorm = (x1.imgMmeanNorm + x2.imgMmeanNorm + x3.imgMmeanNorm + x4.imgMmeanNorm  + x5.imgMmeanNorm)/5;    
     
     data_395S_avg(j).imgSTD = (x1.imgSTD + x2.imgSTD + x3.imgSTD + x4.imgSTD  + x5.imgSTD)/5;
     data_395S_avg(j).imgSTDNorm = (x1.imgSTDNorm + x2.imgSTDNorm + x3.imgSTDNorm + x4.imgSTDNorm  + x5.imgSTDNorm)/5;
     
     data_395S_avg(j).rSTD = (x1.rSTD + x2.rSTD + x3.rSTD + x4.rSTD  + x5.rSTD)/5;
     data_395S_avg(j).gSTD = (x1.gSTD + x2.gSTD + x3.gSTD + x4.gSTD  + x5.gSTD)/5;
     data_395S_avg(j).bSTD = (x1.bSTD + x2.bSTD + x3.bSTD + x4.bSTD  + x5.bSTD)/5;
     data_395S_avg(j).rSTDNorm = (x1.rSTDNorm + x2.rSTDNorm + x3.rSTDNorm + x4.rSTDNorm  + x5.rSTDNorm)/5;
     data_395S_avg(j).gSTDNorm = (x1.gSTDNorm + x2.gSTDNorm + x3.gSTDNorm + x4.gSTDNorm  + x5.gSTDNorm)/5;
     data_395S_avg(j).bSTDNorm = (x1.bSTDNorm + x2.bSTDNorm + x3.bSTDNorm + x4.bSTDNorm  + x5.bSTDNorm)/5;
     
     data_395S_avg(j).imgTLstd = (x1.imgTLstd + x2.imgTLstd + x3.imgTLstd + x4.imgTLstd  + x5.imgTLstd)/5;
     data_395S_avg(j).imgTMstd = (x1.imgTMstd  + x2.imgTMstd  + x3.imgTMstd  + x4.imgTMstd   + x5.imgTMstd)/5;
     data_395S_avg(j).imgLMstd = (x1.imgLMstd + x2.imgLMstd + x3.imgLMstd + x4.imgLMstd  + x5.imgLMstd)/5;
     data_395S_avg(j).imgMstd = (x1.imgMstd + x2.imgMstd + x3.imgMstd + x4.imgMstd  + x5.imgMstd)/5;

     data_395S_avg(j).imgTLstdNorm = (x1.imgTLstdNorm + x2.imgTLstdNorm + x3.imgTLstdNorm + x4.imgTLstdNorm  + x5.imgTLstdNorm)/5;
     data_395S_avg(j).imgTMstdNorm = (x1.imgTMstdNorm  + x2.imgTMstdNorm  + x3.imgTMstdNorm  + x4.imgTMstdNorm   + x5.imgTMstdNorm )/5;
     data_395S_avg(j).imgLMstdNorm = (x1.imgLMstdNorm + x2.imgLMstdNorm + x3.imgLMstdNorm + x4.imgLMstdNorm  + x5.imgLMstdNorm)/5;
     data_395S_avg(j).imgMstdNorm = (x1.imgMstdNorm + x2.imgMstdNorm + x3.imgMstdNorm + x4.imgMstdNorm  + x5.imgMstdNorm)/5;
     
     j = j + 1;  
 end
 
 j = 1;
 for i = 1:5:length(data_798T.exposureTime)
     x1 = data_798S(i);
     x2 = data_798S(i+1);
     x3 = data_798S(i+2);
     x4 = data_798S(i+3);
     x5 = data_798S(i+4);
     
     data_798S_avg(j).imgMean = (x1.imgMean + x2.imgMean + x3.imgMean + x4.imgMean  + x5.imgMean)/5;
     data_798S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     data_798S_avg(j).imgMeanNorm = (x1.imgMeanNorm + x2.imgMeanNorm + x3.imgMeanNorm + x4.imgMeanNorm  + x5.imgMeanNorm)/5;
     data_798S_avg(j).exposureTime = (x1.exposureTime + x2.exposureTime + x3.exposureTime + x4.exposureTime  + x5.exposureTime)/5;
     
     data_798S_avg(j).rMean = (x1.rMean + x2.rMean + x3.rMean + x4.rMean  + x5.rMean)/5;
     data_798S_avg(j).gMean = (x1.gMean + x2.gMean + x3.gMean + x4.gMean  + x5.gMean)/5;
     data_798S_avg(j).bMean = (x1.bMean + x2.bMean + x3.bMean + x4.bMean  + x5.bMean)/5;        
     
     data_798S_avg(j).rMeanNorm = (x1.rMeanNorm + x2.rMeanNorm + x3.rMeanNorm + x4.rMeanNorm  + x5.rMeanNorm)/5;
     data_798S_avg(j).gMeanNorm = (x1.gMeanNorm + x2.gMeanNorm + x3.gMeanNorm + x4.gMeanNorm  + x5.gMeanNorm)/5;
     data_798S_avg(j).bMeanNorm = (x1.bMeanNorm + x2.bMeanNorm + x3.bMeanNorm + x4.bMeanNorm  + x5.bMeanNorm)/5;
        
     data_798S_avg(j).imgTLmean = (x1.imgTLmean + x2.imgTLmean + x3.imgTLmean + x4.imgTLmean  + x5.imgTLmean)/5;
     data_798S_avg(j).imgTMmean = (x1.imgTMmean  + x2.imgTMmean  + x3.imgTMmean  + x4.imgTMmean   + x5.imgTMmean )/5;
     data_798S_avg(j).imgLMmean = (x1.imgLMmean + x2.imgLMmean + x3.imgLMmean + x4.imgLMmean  + x5.imgLMmean)/5;
     data_798S_avg(j).imgMmean = (x1.imgMmean + x2.imgMmean + x3.imgMmean + x4.imgMmean  + x5.imgMmean)/5;
     
     data_798S_avg(j).imgTLmeanNorm = (x1.imgTLmeanNorm + x2.imgTLmeanNorm + x3.imgTLmeanNorm + x4.imgTLmeanNorm  + x5.imgTLmeanNorm)/5;
     data_798S_avg(j).imgTMmeanNorm = (x1.imgTMmeanNorm  + x2.imgTMmeanNorm  + x3.imgTMmeanNorm  + x4.imgTMmeanNorm   + x5.imgTMmeanNorm )/5;
     data_798S_avg(j).imgLMmeanNorm = (x1.imgLMmeanNorm + x2.imgLMmeanNorm + x3.imgLMmeanNorm + x4.imgLMmeanNorm  + x5.imgLMmeanNorm)/5;
     data_798S_avg(j).imgMmeanNorm = (x1.imgMmeanNorm + x2.imgMmeanNorm + x3.imgMmeanNorm + x4.imgMmeanNorm  + x5.imgMmeanNorm)/5;     
     
     data_798S_avg(j).imgSTD = (x1.imgSTD + x2.imgSTD + x3.imgSTD + x4.imgSTD  + x5.imgSTD)/5;
     data_798S_avg(j).imgSTDNorm = (x1.imgSTDNorm + x2.imgSTDNorm + x3.imgSTDNorm + x4.imgSTDNorm  + x5.imgSTDNorm)/5;
     
     data_798S_avg(j).rSTD = (x1.rSTD + x2.rSTD + x3.rSTD + x4.rSTD  + x5.rSTD)/5;
     data_798S_avg(j).gSTD = (x1.gSTD + x2.gSTD + x3.gSTD + x4.gSTD  + x5.gSTD)/5;
     data_798S_avg(j).bSTD = (x1.bSTD + x2.bSTD + x3.bSTD + x4.bSTD  + x5.bSTD)/5;
     data_798S_avg(j).rSTDNorm = (x1.rSTDNorm + x2.rSTDNorm + x3.rSTDNorm + x4.rSTDNorm  + x5.rSTDNorm)/5;
     data_798S_avg(j).gSTDNorm = (x1.gSTDNorm + x2.gSTDNorm + x3.gSTDNorm + x4.gSTDNorm  + x5.gSTDNorm)/5;
     data_798S_avg(j).bSTDNorm = (x1.bSTDNorm + x2.bSTDNorm + x3.bSTDNorm + x4.bSTDNorm  + x5.bSTDNorm)/5;
     
     data_798S_avg(j).imgTLstd = (x1.imgTLstd + x2.imgTLstd + x3.imgTLstd + x4.imgTLstd  + x5.imgTLstd)/5;
     data_798S_avg(j).imgTMstd = (x1.imgTMstd  + x2.imgTMstd  + x3.imgTMstd  + x4.imgTMstd   + x5.imgTMstd)/5;
     data_798S_avg(j).imgLMstd = (x1.imgLMstd + x2.imgLMstd + x3.imgLMstd + x4.imgLMstd  + x5.imgLMstd)/5;
     data_798S_avg(j).imgMstd = (x1.imgMstd + x2.imgMstd + x3.imgMstd + x4.imgMstd  + x5.imgMstd)/5;

     data_798S_avg(j).imgTLstdNorm = (x1.imgTLstdNorm + x2.imgTLstdNorm + x3.imgTLstdNorm + x4.imgTLstdNorm  + x5.imgTLstdNorm)/5;
     data_798S_avg(j).imgTMstdNorm = (x1.imgTMstdNorm  + x2.imgTMstdNorm  + x3.imgTMstdNorm  + x4.imgTMstdNorm   + x5.imgTMstdNorm )/5;
     data_798S_avg(j).imgLMstdNorm = (x1.imgLMstdNorm + x2.imgLMstdNorm + x3.imgLMstdNorm + x4.imgLMstdNorm  + x5.imgLMstdNorm)/5;
     data_798S_avg(j).imgMstdNorm = (x1.imgMstdNorm + x2.imgMstdNorm + x3.imgMstdNorm + x4.imgMstdNorm  + x5.imgMstdNorm)/5;
     
     j = j + 1;  
 end
 
%% Plot Averaged Frame Data

T = struct2table(data_55S_avg); % convert the struct array to a table
data_55T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_99S_avg); % convert the struct array to a table
data_99T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_198S_avg); % convert the struct array to a table
data_198T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_299S_avg); % convert the struct array to a table
data_299T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_395S_avg); % convert the struct array to a table
data_395T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'

T = struct2table(data_798S_avg); % convert the struct array to a table
data_798T_avg = sortrows(T, 'exposureTime'); % sort the table by 'exposureTime'


% NON-NORMALIZED ---- SENSOR ARRAY
figure(1)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.imgMean, 'r', 'DisplayName', '55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', '55')
theString = sprintf('55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(20e-3, 125, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.imgMean, 'r', 'DisplayName', '99')
plot(data_99T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', '99')
theString = sprintf('99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(20e-3, 115, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.imgMean, 'g', 'DisplayName', '198')
plot(data_198T_avg.exposureTime, orig1, '--g', [0 20e-3], xtnd1, '--g', 'DisplayName', '198')
theString = sprintf('198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(20e-3, 105, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.imgMean, 'b', 'DisplayName', '299')
plot(data_299T_avg.exposureTime, orig1, '--b', [0 15e-3], xtnd1, '--b', 'DisplayName', '299')
theString = sprintf('299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(38e-3, 125, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.imgMean, 'c', 'DisplayName', '395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', '395')
theString = sprintf('395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(38e-3, 115, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.imgMean, 'm', 'DisplayName', '798')
plot(data_798T_avg.exposureTime, orig2,'--m', [0 5e-3], xtnd2, '--m', 'DisplayName', '798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(38e-3, 105, theString, 'FontSize', 12);
title('DN vs. Exposure Time (s) : Sensor Array (Not Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off

% NORMALIZED ------ SENSOR ARRAY
figure(2)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
errorbar(data_55T_avg.exposureTime, data_55T_avg.imgMeanNorm, data_55T_avg.imgSTDNorm, '--r', 'DisplayName', '55')
%scatter(data_55T_avg.exposureTime, data_55T_avg.imgMeanNorm, 'r', 'DisplayName', '55')
plot(data_55T_avg.exposureTime, orig1, '--', [0 60e-3], xtnd1, '--r', 'DisplayName', '55')
theString = sprintf('55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(20e-3, 50, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
errorbar(data_99T_avg.exposureTime, data_99T_avg.imgMeanNorm, data_99T_avg.imgSTDNorm, '--g', 'DisplayName', '99')
%scatter(data_99T_avg.exposureTime, data_99T_avg.imgMeanNorm, 'r', 'DisplayName', '99')
plot(data_99T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', '99')
theString = sprintf('99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(20e-3, 40, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
errorbar(data_198T_avg.exposureTime, data_198T_avg.imgMeanNorm, data_198T_avg.imgSTDNorm, '--b',  'DisplayName', '198')
%scatter(data_198T_avg.exposureTime, data_198T_avg.imgMeanNorm, 'g', 'DisplayName', '198')
plot(data_198T_avg.exposureTime, orig1, '--b', [0 20e-3], xtnd1, '--b', 'DisplayName', '198')
theString = sprintf('198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(20e-3, 30, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
errorbar(data_299T_avg.exposureTime, data_299T_avg.imgMeanNorm, data_299T_avg.imgSTDNorm, '--c','DisplayName', '299')
%scatter(data_299T_avg.exposureTime, data_299T_avg.imgMeanNorm, 'b', 'DisplayName', '299')
plot(data_299T_avg.exposureTime, orig1, '--c', [0 15e-3], xtnd1, '--c', 'DisplayName', '299')
theString = sprintf('299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(38e-3, 50, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
errorbar(data_395T_avg.exposureTime, data_395T_avg.imgMeanNorm, data_395T_avg.imgSTDNorm, '--m','DisplayName', '395')
%scatter(data_395T_avg.exposureTime, data_395T_avg.imgMeanNorm, 'c', 'DisplayName', '395')
plot(data_395T_avg.exposureTime, orig1, '--m', [0 10e-3], xtnd1, '--m', 'DisplayName', '395')
theString = sprintf('395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(38e-3, 40, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
errorbar(data_798T_avg.exposureTime, data_798T_avg.imgMeanNorm, data_798T_avg.imgSTDNorm, '--k', 'DisplayName', '798')
%scatter(data_798T_avg.exposureTime, data_798T_avg.imgMeanNorm, 'm', 'DisplayName', '798')
plot(data_798T_avg.exposureTime, orig2,'--k', [0 5e-3], xtnd2, '--k', 'DisplayName', '798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(38e-3, 30, theString, 'FontSize', 12);
title('DN vs. Exposure Time (s) : Sensor Array (Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend

hold off





% NON-NORMALIZED ---- CHANNELS
figure(3)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.rMean, 'r', 'DisplayName', 'r55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'r55')
theString = sprintf('55r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 200, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.gMean, 'g', 'DisplayName', 'g55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'g55')
theString = sprintf('55g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 190, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.bMean, 'b', 'DisplayName', 'b55')
plot(data_55T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'b55')
theString = sprintf('55b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 180, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.rMean, 'r', 'DisplayName', 'r99')
plot(data_99T_avg.exposureTime, orig1, 'r', [0 60e-3], xtnd1, 'r', 'DisplayName', 'r99')
theString = sprintf('99r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 170, theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.gMean, 'g', 'DisplayName', 'g99')
plot(data_99T_avg.exposureTime, orig1, 'g', [0 60e-3], xtnd1, 'g', 'DisplayName', 'g99')
theString = sprintf('99g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 160, theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.bMean, 'b', 'DisplayName', 'b99')
plot(data_99T_avg.exposureTime, orig1, 'b', [0 60e-3], xtnd1, 'b', 'DisplayName', 'b99')
theString = sprintf('99b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 150, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.rMean, 'r', 'DisplayName', 'r198')
plot(data_198T_avg.exposureTime, orig1, '-.r', [0 20e-3], xtnd1, '-.r', 'DisplayName', 'r198')
theString = sprintf('198r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 200, theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.gMean, 'g', 'DisplayName', 'g198')
plot(data_198T_avg.exposureTime, orig1, '-.g', [0 20e-3], xtnd1, '-.g', 'DisplayName', 'g198')
theString = sprintf('198g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 190, theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.bMean, 'b', 'DisplayName', 'b198')
plot(data_198T_avg.exposureTime, orig1, '-.b', [0 20e-3], xtnd1, '-.b', 'DisplayName', 'b198')
theString = sprintf('198b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 180, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.rMean, 'r', 'DisplayName', 'r299')
plot(data_299T_avg.exposureTime, orig1, ':r', [0 15e-3], xtnd1, ':r', 'DisplayName', 'r299')
theString = sprintf('299r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 170, theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.gMean, 'g', 'DisplayName', 'g299')
plot(data_299T_avg.exposureTime, orig1, ':g', [0 15e-3], xtnd1, ':g', 'DisplayName', 'g299')
theString = sprintf('299g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 160, theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.bMean, 'b', 'DisplayName', 'b299')
plot(data_299T_avg.exposureTime, orig1, ':b', [0 15e-3], xtnd1, ':b', 'DisplayName', 'b299')
theString = sprintf('299b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 150, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.rMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.rMean, 'c', 'DisplayName', 'r395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', 'r395')
theString = sprintf('395r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 200, theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.gMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.gMean, 'm', 'DisplayName', 'g395')
plot(data_395T_avg.exposureTime, orig1, '--m', [0 10e-3], xtnd1, '--m', 'DisplayName', 'g395')
theString = sprintf('395g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 190, theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.bMean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.bMean, 'k', 'DisplayName', 'b395')
plot(data_395T_avg.exposureTime, orig1, '--k', [0 10e-3], xtnd1, '--k', 'DisplayName', 'b395')
theString = sprintf('395b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 180, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.rMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.rMean, 'c', 'DisplayName', 'r798')
plot(data_798T_avg.exposureTime, orig2,'c', [0 5e-3], xtnd2, 'c', 'DisplayName', 'r798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798r: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 170, theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.gMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.gMean, 'm', 'DisplayName', 'g798')
plot(data_798T_avg.exposureTime, orig2,'m', [0 5e-3], xtnd2, 'm', 'DisplayName', 'g798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798g: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 160, theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.bMean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.bMean, 'k', 'DisplayName', 'b798')
plot(data_798T_avg.exposureTime, orig2,'k', [0 5e-3], xtnd2, 'k', 'DisplayName', 'b798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798b: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 150, theString, 'FontSize', 12);

title('DN vs. Exposure Time (s) : Sensor Channels (Not Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off

% NORMALIZED ------ CHANNELS
figure(4)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.rMeanNorm, 'r', 'DisplayName', 'r55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'r55')
theString = sprintf('55r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 60, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.gMeanNorm, 'g', 'DisplayName', 'g55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'g55')
theString = sprintf('55g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 50, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.bMeanNorm, 'b', 'DisplayName', 'b55')
plot(data_55T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'b55')
theString = sprintf('55b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 40, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.rMeanNorm, 'r', 'DisplayName', 'r99')
plot(data_99T_avg.exposureTime, orig1, 'r', [0 60e-3], xtnd1, 'r', 'DisplayName', 'r99')
theString = sprintf('99r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 30, theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.gMeanNorm, 'g', 'DisplayName', 'g99')
plot(data_99T_avg.exposureTime, orig1, 'g', [0 60e-3], xtnd1, 'g', 'DisplayName', 'g99')
theString = sprintf('99g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 20, theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.bMeanNorm, 'b', 'DisplayName', 'b99')
plot(data_99T_avg.exposureTime, orig1, 'b', [0 60e-3], xtnd1, 'b', 'DisplayName', 'b99')
theString = sprintf('99b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 10, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.rMeanNorm, 'r', 'DisplayName', 'r198')
plot(data_198T_avg.exposureTime, orig1, '-.r', [0 20e-3], xtnd1, '-.r', 'DisplayName', 'r198')
theString = sprintf('198r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 60, theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.gMeanNorm, 'g', 'DisplayName', 'g198')
plot(data_198T_avg.exposureTime, orig1, '-.g', [0 20e-3], xtnd1, '-.g', 'DisplayName', 'g198')
theString = sprintf('198g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 50, theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.bMeanNorm, 'b', 'DisplayName', 'b198')
plot(data_198T_avg.exposureTime, orig1, '-.b', [0 20e-3], xtnd1, '-.b', 'DisplayName', 'b198')
theString = sprintf('198b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 40, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.rMeanNorm, 'r', 'DisplayName', 'r299')
plot(data_299T_avg.exposureTime, orig1, ':r', [0 15e-3], xtnd1, ':r', 'DisplayName', 'r299')
theString = sprintf('299r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 30, theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.gMeanNorm, 'g', 'DisplayName', 'g299')
plot(data_299T_avg.exposureTime, orig1, ':g', [0 15e-3], xtnd1, ':g', 'DisplayName', 'g299')
theString = sprintf('299g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 20, theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.bMeanNorm, 'b', 'DisplayName', 'b299')
plot(data_299T_avg.exposureTime, orig1, ':b', [0 15e-3], xtnd1, ':b', 'DisplayName', 'b299')
theString = sprintf('299b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 10, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.rMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.rMeanNorm, 'c', 'DisplayName', 'r395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', 'r395')
theString = sprintf('395r: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 60, theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.gMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.gMeanNorm, 'm', 'DisplayName', 'g395')
plot(data_395T_avg.exposureTime, orig1, '--m', [0 10e-3], xtnd1, '--m', 'DisplayName', 'g395')
theString = sprintf('395g: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 50, theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.bMeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.bMeanNorm, 'k', 'DisplayName', 'b395')
plot(data_395T_avg.exposureTime, orig1, '--k', [0 10e-3], xtnd1, '--k', 'DisplayName', 'b395')
theString = sprintf('395b: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 40, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.rMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.rMeanNorm, 'c', 'DisplayName', 'r798')
plot(data_798T_avg.exposureTime, orig2,'--c', [0 5e-3], xtnd2, '--c', 'DisplayName', 'r798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798r: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 30, theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.gMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.gMeanNorm, 'm', 'DisplayName', 'g798')
plot(data_798T_avg.exposureTime, orig2,'--m', [0 5e-3], xtnd2, '--m', 'DisplayName', 'g798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798g: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 20, theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.bMeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.bMeanNorm, 'k', 'DisplayName', 'b798')
plot(data_798T_avg.exposureTime, orig2,'--k', [0 5e-3], xtnd2, '--k', 'DisplayName', 'b798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('798b: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 10, theString, 'FontSize', 12);

title('DN vs. Exposure Time (s) : Sensor Channels (Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off



% NON-NORMALIZED ---- SENSOR LOCATION
figure(5)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.imgTLmean, 'r', 'DisplayName', 'TL55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'TL55')
theString = sprintf('TL55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 200, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
scatter(data_55T_avg.exposureTime, data_55T_avg.imgMmean, 'g', 'DisplayName', 'M55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'M55')
theString = sprintf('M55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 190, theString, 'FontSize', 12);




% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.imgTLmean, 'b', 'DisplayName', 'TL99')
plot(data_99T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'TL99')
theString = sprintf('TL99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 170, theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
scatter(data_99T_avg.exposureTime, data_99T_avg.imgMmean, 'c', 'DisplayName', 'M99')
plot(data_99T_avg.exposureTime, orig1, '--c', [0 60e-3], xtnd1, '--c', 'DisplayName', 'M99')
theString = sprintf('M99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, 160, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.imgTLmean, 'm', 'DisplayName', 'TL198')
plot(data_198T_avg.exposureTime, orig1, '--m', [0 20e-3], xtnd1, '--m', 'DisplayName', 'TL198')
theString = sprintf('TL198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 200, theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
scatter(data_198T_avg.exposureTime, data_198T_avg.imgMmean, 'k', 'DisplayName', 'M198')
plot(data_198T_avg.exposureTime, orig1, '--k', [0 20e-3], xtnd1, '--k', 'DisplayName', 'M198')
theString = sprintf('M198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 190, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.imgTLmean, 'r', 'DisplayName', 'TL299')
plot(data_299T_avg.exposureTime, orig1, 'r', [0 15e-3], xtnd1, 'r', 'DisplayName', 'TL299')
theString = sprintf('TL299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 170, theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
scatter(data_299T_avg.exposureTime, data_299T_avg.imgMmean, 'g', 'DisplayName', 'M299')
plot(data_299T_avg.exposureTime, orig1, 'g', [0 15e-3], xtnd1, 'g', 'DisplayName', 'M299')
theString = sprintf('M299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, 160, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgTLmean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.imgTLmean, 'b', 'DisplayName', 'TL395')
plot(data_395T_avg.exposureTime, orig1, 'b', [0 10e-3], xtnd1, 'b', 'DisplayName', 'TL395')
theString = sprintf('TL395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 200, theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMmean, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
scatter(data_395T_avg.exposureTime, data_395T_avg.imgMmean, 'c', 'DisplayName', 'M395')
plot(data_395T_avg.exposureTime, orig1, 'c', [0 10e-3], xtnd1, 'c', 'DisplayName', 'M395')
theString = sprintf('M395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, 190, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgTLmean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.imgTLmean, 'm', 'DisplayName', 'TL798')
plot(data_798T_avg.exposureTime, orig2,'m', [0 5e-3], xtnd2, 'm', 'DisplayName', 'TL798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('TL798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 170, theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMmean, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
scatter(data_798T_avg.exposureTime, data_798T_avg.imgMmean, 'r', 'DisplayName', 'M798')
plot(data_798T_avg.exposureTime, orig2,'-.r', [0 5e-3], xtnd2, '-.r', 'DisplayName', 'M798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('M798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, 160, theString, 'FontSize', 12);


title('DN vs. Exposure Time (s) : Sensor Location (Not Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off



% NORMALIZED ---- SENSOR LOCATION
figure(6)
hold on
% Plot a single ISOSpeed - 55
bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
errorbar(data_55T_avg.exposureTime, data_55T_avg.imgTLmeanNorm, data_55T_avg.imgTLstdNorm, '--r', 'DisplayName', 'TL55')
%scatter(data_55T_avg.exposureTime, data_55T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL55')
plot(data_55T_avg.exposureTime, orig1, '--r', [0 60e-3], xtnd1, '--r', 'DisplayName', 'TL55')
theString = sprintf('TL55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, -10, theString, 'FontSize', 12);

bestfit1 = polyfit(data_55T_avg.exposureTime, data_55T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_55T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_55T_avg.exposureTime + bestfit1(2);
errorbar(data_55T_avg.exposureTime, data_55T_avg.imgMmeanNorm, data_55T_avg.imgMstdNorm, '--g', 'DisplayName', 'M55')
%scatter(data_55T_avg.exposureTime, data_55T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M55')
plot(data_55T_avg.exposureTime, orig1, '--g', [0 60e-3], xtnd1, '--g', 'DisplayName', 'M55')
theString = sprintf('M55: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, -20, theString, 'FontSize', 12);




% Plot a single ISOSpeed - 99
bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
errorbar(data_99T_avg.exposureTime, data_99T_avg.imgTLmeanNorm, data_99T_avg.imgTLstdNorm, '--b', 'DisplayName', 'TL99')
%scatter(data_99T_avg.exposureTime, data_99T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL99')
plot(data_99T_avg.exposureTime, orig1, '--b', [0 60e-3], xtnd1, '--b', 'DisplayName', 'TL99')
theString = sprintf('TL99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, -40, theString, 'FontSize', 12);

bestfit1 = polyfit(data_99T_avg.exposureTime, data_99T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_99T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 60e-3]);
disp_pr_s = bestfit1(1)*data_99T_avg.exposureTime + bestfit1(2);
errorbar(data_99T_avg.exposureTime, data_99T_avg.imgMmeanNorm, data_99T_avg.imgMstdNorm, 'r', 'DisplayName', 'M99')
%scatter(data_99T_avg.exposureTime, data_99T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M99')
plot(data_99T_avg.exposureTime, orig1, 'r', [0 60e-3], xtnd1, 'r', 'DisplayName', 'M99')
theString = sprintf('M99: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(10e-3, -50, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 198
bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
errorbar(data_198T_avg.exposureTime, data_198T_avg.imgTLmeanNorm, data_198T_avg.imgTLstdNorm, 'g', 'DisplayName', 'TL198')
%scatter(data_198T_avg.exposureTime, data_198T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL198')
plot(data_198T_avg.exposureTime, orig1, 'g', [0 20e-3], xtnd1, 'g', 'DisplayName', 'TL198')
theString = sprintf('TL198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, -10, theString, 'FontSize', 12);

bestfit1 = polyfit(data_198T_avg.exposureTime, data_198T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_198T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 20e-3]);
disp_pr_s = bestfit1(1)*data_198T_avg.exposureTime + bestfit1(2);
errorbar(data_198T_avg.exposureTime, data_198T_avg.imgMmeanNorm, data_198T_avg.imgMstdNorm, 'b',  'DisplayName', 'M198')
%scatter(data_198T_avg.exposureTime, data_198T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M198')
plot(data_198T_avg.exposureTime, orig1, 'b', [0 20e-3], xtnd1, 'b', 'DisplayName', 'M198')
theString = sprintf('M198: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, -20, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 299
bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
errorbar(data_299T_avg.exposureTime, data_299T_avg.imgTLmeanNorm, data_299T_avg.imgTLstdNorm, '-.r', 'DisplayName', 'TL299')
%scatter(data_299T_avg.exposureTime, data_299T_avg.imgTLmeanNorm, 'b', 'DisplayName', 'TL299')
plot(data_299T_avg.exposureTime, orig1, '-.r', [0 15e-3], xtnd1, '-.r', 'DisplayName', 'TL299')
theString = sprintf('TL299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, -40, theString, 'FontSize', 12);

bestfit1 = polyfit(data_299T_avg.exposureTime, data_299T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_299T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 15e-3]);
disp_pr_s = bestfit1(1)*data_299T_avg.exposureTime + bestfit1(2);
errorbar(data_299T_avg.exposureTime, data_299T_avg.imgMmeanNorm, data_299T_avg.imgMstdNorm,'-.g', 'DisplayName', 'M299')
%scatter(data_299T_avg.exposureTime, data_299T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M299')
plot(data_299T_avg.exposureTime, orig1, '-.g', [0 15e-3], xtnd1, '-.g', 'DisplayName', 'M299')
theString = sprintf('M299: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(25e-3, -50, theString, 'FontSize', 12);

% Plot a single ISOSpeed - 395
bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgTLmeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
errorbar(data_395T_avg.exposureTime, data_395T_avg.imgTLmeanNorm, data_395T_avg.imgTLstdNorm, '-.b', 'DisplayName', 'TL395')
%scatter(data_395T_avg.exposureTime, data_395T_avg.imgTLmeanNorm, 'b', 'DisplayName', 'TL395')
plot(data_395T_avg.exposureTime, orig1, '-.b', [0 10e-3], xtnd1, '-.b', 'DisplayName', 'TL395')
theString = sprintf('TL395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, -10, theString, 'FontSize', 12);

bestfit1 = polyfit(data_395T_avg.exposureTime, data_395T_avg.imgMmeanNorm, 1);
orig1 = polyval(bestfit1, data_395T_avg.exposureTime);
xtnd1 = polyval(bestfit1, [0 10e-3]);
disp_pr_s = bestfit1(1)*data_395T_avg.exposureTime + bestfit1(2);
errorbar(data_395T_avg.exposureTime, data_395T_avg.imgMmeanNorm, data_395T_avg.imgMstdNorm, '--c', 'DisplayName', 'M395')
%scatter(data_395T_avg.exposureTime, data_395T_avg.imgMmeanNorm, 'c', 'DisplayName', 'M395')
plot(data_395T_avg.exposureTime, orig1, '--c', [0 10e-3], xtnd1, '--c', 'DisplayName', 'M395')
theString = sprintf('M395: y = %.3f x + %.3f', bestfit1(1), bestfit1(2));
text(40e-3, -20, theString, 'FontSize', 12);


% Plot a single ISOSpeed - 798
bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgTLmeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
errorbar(data_798T_avg.exposureTime, data_798T_avg.imgTLmeanNorm, data_798T_avg.imgTLstdNorm,'--m', 'DisplayName', 'TL798')
%scatter(data_798T_avg.exposureTime, data_798T_avg.imgTLmeanNorm, 'r', 'DisplayName', 'TL798')
plot(data_798T_avg.exposureTime, orig2,'--m', [0 5e-3], xtnd2, '--m', 'DisplayName', 'TL798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('TL798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, -40, theString, 'FontSize', 12);

bestfit2 = polyfit(data_798T_avg.exposureTime, data_798T_avg.imgMmeanNorm, 1);
orig2 = polyval(bestfit2, data_798T_avg.exposureTime);
xtnd2 = polyval(bestfit2, [0 5e-3]);
disp_pr_s = bestfit2(1)*data_798T_avg.exposureTime + bestfit2(2);
errorbar(data_798T_avg.exposureTime, data_798T_avg.imgMmeanNorm, data_798T_avg.imgMstdNorm, '--k',  'DisplayName', 'M798')
%scatter(data_798T_avg.exposureTime, data_798T_avg.imgMmeanNorm, 'g', 'DisplayName', 'M798')
plot(data_798T_avg.exposureTime, orig2,'--k', [0 5e-3], xtnd2, '--k', 'DisplayName', 'M798')
%plot(data_798T_avg.exposureTime, xtnd2, '--m', 'DisplayName', '798')
theString = sprintf('M798: y = %.3f x + %.3f', bestfit2(1), bestfit2(2));
text(40e-3, -50, theString, 'FontSize', 12);


title('DN vs. Exposure Time (s) : Sensor Location (Normalized)')
xlabel('Exposure Time (s)')
ylabel('Digital Number (16-bit FS)')
legend


hold off